# Generated by Django 4.1.1 on 2023-01-10 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('wallet', models.CharField(blank=True, max_length=100)),
                ('hex_address', models.CharField(blank=True, max_length=100)),
                ('private_key', models.CharField(blank=True, max_length=100)),
                ('public_key', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('user_names', models.CharField(blank=True, max_length=100)),
                ('tariff', models.CharField(blank=True, max_length=100)),
                ('numbers', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.TextField()),
                ('gender', models.CharField(choices=[('0', 'Indonesia account 1'), ('1', 'Vietnam account'), ('2', 'Indonesia account 2')], default=1, max_length=20)),
                ('contact', models.CharField(blank=True, max_length=128)),
                ('file', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
