# Generated by Django 4.1.1 on 2023-01-10 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
