# Generated by Django 4.1.1 on 2023-01-10 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_alter_subscriber_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_send',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
